SAMPLE_RATE = 48000
NUDGE_STEP_SECONDS = 0.05
NUDGE_STEP_SAMPLES = int(SAMPLE_RATE * NUDGE_STEP_SECONDS)
POSITION_TOLERANCE_SAMPLES = 2

MAIN_VIDEO_TRACK = "main_video"
SECONDARY_VIDEO_TRACK = "secondary_video"
SOUND_EFFECTS_TRACK = "sound_effects"
BACKGROUND_AUDIO_TRACK = "background_audio"
TEXT_TRACK = "text"

TRACK_ORDER = (
    MAIN_VIDEO_TRACK,
    SECONDARY_VIDEO_TRACK,
    SOUND_EFFECTS_TRACK,
    BACKGROUND_AUDIO_TRACK,
    TEXT_TRACK,
)

MAIN_ACCEPTED_MEDIA_TYPES = ("video", "image")

TRACK_ACCEPTED_MEDIA_TYPES = {
    SECONDARY_VIDEO_TRACK: ("video", "image"),
    SOUND_EFFECTS_TRACK: ("audio",),
    BACKGROUND_AUDIO_TRACK: ("audio",),
    TEXT_TRACK: ("text",),
}

RIPPLE_MODE_PER_TRACK = "per_track"
RIPPLE_MODE_ALL_TRACKS = "all_tracks"
RIPPLE_MODE_OFF = "off"
